# Conclusiones

Del análisis exploratorio podemos extraer mucha información general del dataset. Los archivos tienen un tamaño medio de unos 6MB y vienen en formato ZIP, entre quince y veinticinco antivirus los detectan como positivos de media y la gran mayoría se han subido en 2021. 


El análisis del ssdeep ha mostrado en primer lugar que hay catorce archivos cuya distancia es uno o cero. Indicando por lo tanto que se trata prácticamente del mismo archivo, esto puede deberse a que alguien se haya dedicado a subir muchas veces el mismo archivo con pequeñas modificaciones. Fueron subidos todos desde Canadá en poco tiempo, el tamaño solo difiere en un archivo y todos fueron vistos por primera la vez que fueron escaneados, no fueron subidos nunca antes.
Sin embargo, los antivirus han dado distintos resultado cada vez (manteniendo entre 19 y 22 positivos). 

Del grafo G1 se ha obtenido un componente de 99 que comparten al menos un 60% de código, lo que es más del dataset. Al analizar este componente hay varios nodos que tienen un grado muy alto, lo que quiere decir que comparten código con muchos otros nodos. Este caso es parecido al grafo de antes, se subieron los 99 archivos en un intervalo de nueve horas (unos once por hora) casi todos desde Bolivia y algunas desde República Checa y Canadá. A pesar de que Bolivia subió la gran parte, República Checa es el que suma mayor tasa de positivos.
 
Al calcular los componentes de G1, al ser un no dirigido lo único que hacemos es buscar vértices desde donde se puede llegar a cualquier otro vértice por algún camino. Se han encontrado dos grandes componentes de tamaños 12 y 99. Dentro del componente de 99 a su vez se observa que se forman subgrupos, como por la forma de construir el grafo sabemos que aquellos que están conectados sabemos tienen similitudes en su código, estos subgrupos pueden ser pequeñas variantes del mismo *malware*.

Del grafo G se obtienen conclusiones parecidas, son 27 archivos muy parecidos subidos en menos de una hora con unos veinte positivos de media. Igual que antes, lo más seguro es que se trate de la misma persona subiendo 27 veces lo mismo con pequeñas modificaciones.

Hay que decir que aunque apriori parezcan muchos json, este análisis ha mostrado que realmente son pocos los archivos distintos entre sí. 

Para finalizar este capítulo se aprovechan los grafos para ver cómo han clasificado los antivirus esos archivos que sabemos que son casi idénticos. Si hay varios que los clasifican igual o muy parecido, podemos sospechar que comparten motor. 

No obstante, no parece que los antivirus sigan algún patrón para clasificar, de hecho en algunos parecen cadenas de caracteres aleatorias. De ahí que analizar estos resultados es bastante complicado. La mayoría de los AV parace estar de acuerdo en que los archivos del grafo G son *Adware*, otros dicen que son troyanos. Lo interesante es que se ha podido ver con claridad que tanto *Kaspersky* como *ZoneAlarm* lo clasifican casi igual, lo mismo pasa con *McAfee* y *McAfee-GW-Edition*. Por tanto es muy probable que los dos primeros compartan motor, y es seguro que los dos últimos lo hagan (son de la misma empresa).

En la parte de regresion y clustering hemos tratado de indentificar si el numero de positivos registrado por un archivo de los analizados tenia algo que ver con el tamaño de este. Tras los analisis realizados hemos llegado a la conclusión de que no existe una relacion clara. Es cierto que muestra que cuanto mayor peso tiene el archivo menos positivos obtenemos pero esto viene dado por que hay menos archivos analizados con un peso mayor.

De la parte de reglas, al calcular las reglas hemos obtenido que tienen un soporte y una confianza por debajo del 30% de media.
Hemos analizado tambien y como vimos en el analisis exploratorio, la mayoria de archivos subidos se han subido en 2021, pues de aquí hemos extraido que en el 63,3% de las veces que el año es 2021 el archivo es ZIP.También hemos podido confirmar que República Checa siempre envia DEX como tipo de archivo.
 
